title: System Core TypeScript Library
description: Core types for the system framework
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
    private: true

header_pages:
 - index.md
 - libraries.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

minima:
  date_format: "%Y-%m-%d"
